export const SET_CAST = 'SET_CAST';
export const FETCH_CAST_FAILED = 'FETCH_CAST_FAILED';

export const FETCH_WIKIPEDIA_SUCCESS = 'FETCH_WIKIPEDIA_SUCCESS'
export const FETCH_WIKIPEDIA_FAILED = 'FETCH_WIKIPEDIA_FAILED'
export const CLEAR_WIKIPEDIA_INFO = 'CLEAR_WIKIPEDIA_INFO'